### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hit9** [hit9/skylark#7]
Todo:
1.  [x] concat
2. [x] single filed functions: abs etc
3. [ ]  **fields** for model
4. [x] `count(distinct field)` implementation
5. [x] redesign aggregate functions fetching value way
6. [x] select sub query
7. [ ]  field both primarykey and foreignkey
8. [x] add distinct key word to curd.py
9. [x] add module level shortcut `count`, ..
